config/routes.rb
Photogur::Application.routes.draw do
  resources :pictures
  root :to => "pictures#index"
end

$end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
#class PicturesController < ApplicationController
# def show
#   @pictures = [
#     {
#       :title  => "The old church on the coast of White sea",
#       :artist => "Sergey Ershov",
#       :url    => "http://monicao.s3.amazonaws.com/bitmaker/house.jpg"
#     },
#     {
#       :title  => "Sea Power",
#       :artist => "Stephen Scullion",
#       :url    => "http://monicao.s3.amazonaws.com/bitmaker/wave.jpg"
#     },
#     {
#       :title  => "Into the Poppies",
#       :artist => "John Wilhelm",
#       :url    => "http://monicao.s3.amazonaws.com/bitmaker/girl.jpg"
#     }
#   ]
#   @picture = @pictures[params[:id].to_i]
# end

# def new
# end

# def create
#   render :text => "Saving a picture. URL: #{params[:url]}, Title: #{params[:title]}, Artist: #{params[:artist]}"
# end

class PicturesController < ApplicationController

	def index
	    @picture = Picture.all
	end

	def show
	    @picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

  	def create
  		# Make the variable @picture a new picture with the given params
		@picture = Picture.new(params[:picture])
		if @picture.save
	    	# if the save for the picture was successful, go to index.html.erb
	    	redirect_to pictures_url
		else
	    	# otherwise render the view associated with the action :new (i.e. new.html.erb)
	    	render :new
  		end
	end
	def edit
  		@picture = Picture.find(params[:id])
	end

	def update
  		@picture = Picture.find(params[:id])

  		if @picture.update_attributes(params[:picture])
    		redirect_to "/pictures/#{@picture.id}"
  		else
    		render :edit
  		end
	end
	def destroy
	  @picture = Picture.find(params[:id])
	  @picture.destroy
	  redirect_to pictures_url
	end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @picture.length %>)</h1>
<%= link_to "New picture", "/pictures/new" %>

<% @picture.each do |picture| %>
  <p>Title: <%= picture[:title] %>, Artist: <%= picture[:artist] %></p>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/picture1.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

app/views/pictures/picture2.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<%= image_tag @picture.url %>